services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports: ["1883:1883"]
    networks:
      - net-nodered
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  sim:
    build: ./sim
    image: profilgusto/bioreactor-sim:latest
    container_name: bioreactor-sim
    depends_on: [mqtt]
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - TICK_MS=200
      - UI_ENABLED=true
      - UI_PORT=8000
      - SEED=42
    ports:
      - "8000:8000"   # UI do simulador
    networks:
      - net-nodered
    volumes:
      - ./ui:/app/ui:ro
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health').status==200 else sys.exit(1)\""]
      interval: 10s
      timeout: 2s
      retries: 5

networks: 
  net-nodered: 
    driver: bridge 
